[features]
seeds = false
skip-lint = false
[programs.localnet]
project2 = "7gugESb2Dy7AwDSTMnipaxLB3W1smBhztGWCohGrMWUK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/maxwell/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
